replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
logLevel: INFO
image:
  repository: rancher/opa-gatekeeper
  tag: v3.1.0-beta.8
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
podAnnotations: {
  container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
}
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
global:
  systemDefaultRegistry: ""
  kubectl:
    repository: rancher/istio-kubectl
    tag: 1.4.6
