# base chart url
base: "https://storage.googleapis.com/k3s-chart-testing-2/istio-operator/istio-operator-1.5.0.tar.gz"
crdManifest: |-
  apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: istiooperators.install.istio.io
  spec:
    group: install.istio.io
    versions:
      - name: v1alpha1
        served: true
        storage: true
    scope: Namespaced
    subresources:
      status: {}
    names:
      kind: IstioOperator
      listKind: IstioOperatorList
      plural: istiooperators
      singular: istiooperator
      shortNames:
      - iop
rbacManifest: |-
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: istio-operator
  rules:
  # istio groups
  - apiGroups:
    - authentication.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - config.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - install.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - networking.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - rbac.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups:
    - security.istio.io
    resources:
    - '*'
    verbs:
    - '*'
  # k8s groups
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - '*'
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions.apiextensions.k8s.io
    - customresourcedefinitions
    verbs:
    - '*'
  - apiGroups:
    - apps
    - extensions
    resources:
    - daemonsets
    - deployments
    - deployments/finalizers
    - ingresses
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - autoscaling
    resources:
    - horizontalpodautoscalers
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - '*'
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    - clusterroles
    - roles
    - rolebindings
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - configmaps
    - endpoints
    - events
    - namespaces
    - pods
    - persistentvolumeclaims
    - secrets
    - services
    - serviceaccounts
    verbs:
    - '*'
  ...
  ---
preDeleteCommand:
- "kubectl delete istiooperators.install.istio.io -n istio-system --all"
patches:
- name: system-namespace.patch
  path: templates/istio-operator.yaml
  url: "https://storage.googleapis.com/k3s-chart-testing-2/istio-operator/istio-operator.patch"
