apiVersion: v1
appVersion: 1.5.0
description: Istio Operator
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- security
- sidecarInjectorWebhook
- mixer
- pilot
- galley
name: istio-operator
sources:
- http://github.com/istio/istio
version: 1.5.0