replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
image:
  repository: quay.io/open-policy-agent/gatekeeper
  release: v3.1.0-beta.7
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
podAnnotations: {
  container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
}
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
