#!/usr/bin/env bash
set -x
set -e

for f in packages/*; do
  if [[ -f ${f}/package.yaml ]]; then
    url=$(cat ${f}/package.yaml | yq r - base)
    rm -rf ${f}/charts-modified
    mkdir -p ${f}/charts-modified
    curl -sLf ${url} | tar xvzf - -C ${f}/charts-modified --strip 1
    cd ${f}/charts-modified
    for file in ${f}/*.patch; do
      patch -f -p3 < ../$(basename -- ${file})
    done
    cd ../../..
  fi
done