#!/usr/bin/env bash

# Download helm
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# Download yq
curl -sLf https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 > /usr/local/bin/yq