#!/usr/bin/env bash
set -e

# Download helm
if [[ -z $(command -v helm) ]] || [[ $(helm version --short) != "v3"* ]]; then
	curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
fi

# Download yq
if [[ -z $(command -v yq) ]]; then
	curl -sLf https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 > /usr/local/bin/yq
fi