#!/usr/bin/env bash

for f in packages/*; do
  if [[ -f ${f}/package.yaml ]]; then
    url=$(cat ${f}/package.yaml | yq r - base)
    mkdir -p ${f}/charts-original
    curl -sLf ${url} | tar xvzf - -C ${f}/charts-original --strip 1 > /dev/null 2>&1
    if [[ -d ${f}/charts-modified ]]; then
      diff -Nr ${f}/charts-original ${f}/charts-modified > ${f}/$(basename -- ${f}).patch; true
    fi
  fi
done