#!/usr/bin/env bash

for f in packages/*; do
    mkdir -p docs/$(basename -- ${f})
    helm package ./packages/$(basename -- ${f})/charts-modified --destination docs/$(basename -- ${f})
done

helm repo index docs --url https://strongmonkey.github.com/k3chart
