#!/usr/bin/env bash
set -e
set -x

# rebase the patch with upsteam charts defined in package.yaml. Make sure patches still apply
# for the latest upsteam charts. If there is conflits commiter should solve it.

for f in packages/*; do
  if [[ -f ${f}/package.yaml ]]; then
    url=$(cat ${f}/package.yaml | yq r - url)
    subdirectory=$(cat ${f}/package.yaml | yq r - subdirectory)
    type=$(cat ${f}/package.yaml | yq r - type)
    fields=$(echo ${subdirectory} | awk -F'/' '{print NF}')
    if [[ $fields -eq '0' ]]; then
    	fields='1'
    fi
    rm -rf ${f}/charts
    mkdir -p ${f}/charts
    if [[ $type == 'git' ]]; then
    	mkdir -p /tmp/tmp-charts
			git clone $url /tmp/tmp-charts
			cp -r /tmp/tmp-charts/${subdirectory}/* ${f}/charts
			rm -rf /tmp/tmp-charts
    else
    	curl -sLf ${url} | tar xvzf - -C ${f}/charts --strip ${fields} ${subdirectory} > /dev/null 2>&1
    fi
    for file in $(find ./${f} -type f -name "*.patch"); do
    	basename=$(basename -- ${file})
      patch -p3 -d ${f}/charts < ${f}/$basename
    done
  fi
done