#!/usr/bin/env bash
set -e

# rebase the patch with upsteam charts defined in package.yaml. Make sure patches still apply
# for the latest upsteam charts. If there is conflits commiter should solve it.

for f in packages/*; do
  if [[ -f ${f}/package.yaml ]]; then
    url=$(cat ${f}/package.yaml | yq r - url)
    subdirectory=$(cat ${f}/package.yaml | yq r - subdirectory)
    fields=$(echo ${subdirectory} | awk -F'/' '{print NF}')
    if [[ $fields -eq '0' ]]; then
    	fields='1'
    fi
    rm -rf ${f}/charts
    mkdir -p ${f}/charts
    curl -sLf ${url} | tar xvzf - -C ${f}/charts --strip ${fields} ${subdirectory} > /dev/null 2>&1
    for file in $(find ./${f} -type f -name "*.patch"); do
    	basename=$(basename -- ${file})
    	cd ${f}/charts
      patch -p3 < ../$basename
      cd ../../../
    done
  fi
done