#!/bin/bash
set -e

cd $(dirname $0)/..

for f in packages/*; do
  ./scripts/generate-patch $(basename -- ${f})
done

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    exit 1
fi