{{- if and .Values.rbac.create .Values.rbac.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "external-dns.serviceAccountName" . }}
  labels: {{ include "external-dns.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccountAnnotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
