url: https://charts.bitnami.com/bitnami/external-dns-2.20.10.tgz
packageVersion: 00
imageMirror:
- name: rancher/kubernetes-external-dns
  images:
  - arch: amd64
    os: linux
    original: us.gcr.io/k8s-artifacts-prod/external-dns/external-dns
    tag: v0.6.0